language: python

virtualenv:
  system_site_packages: true

sudo: required

services:
  - docker

before_install:
  - pip install -U setuptools
  - git clone --recurse-submodules git://github.com/openmicroscopy/omero-test-infra .omero

script:
  - .omero/cli-docker

deploy:
  provider: pypi
  user: ${CI_DEPLOY_USER}
  password: ${CI_DEPLOY_PASS}
  server: https://test.pypi.org/legacy/
  on:
    tags: true
